---
# This Play does a hygiene check on whether the cluster machines can be created
#
# ASSUMPTIONS:
# Will make use of sudo password in the configs/password.yml in clear text
#

- name: Validating cluster sanity
  hosts: localhost
  become: no
  vars_files:
    - 'configs/password.yml'
    - 'configs/vms-config.yml'

  vars:
    ansible_become_password: "{{ sudo_password }}"

  tasks:
    - name: Reset HA parameters
      copy:
        content: |
          ha_cluster: false
        dest: configs/ha.yml
      
    - name: Checking total master
      assert:
        that:
          - item.value.count|int > 0 
          - item.value.count|int % 2 != 0
        msg: "k8s masters count should be a positive odd number i.e. 1, 3, 5 etc"
      loop: "{{ lookup('dict',vmg_vms_infra, wantlist=True) }}"
      when: item.key | regex_search('(master)') == 'master'
      loop_control:
        label: output

    - name: Checking for HA requirements
      copy:
        content: |
          ha_cluster: true
        dest: configs/ha.yml
      loop: "{{ lookup('dict',vmg_vms_infra, wantlist=True) }}"
      when: item.key | regex_search('(master)') == 'master' and item.value.count|int >= 3
      loop_control:
        label: output


    - name: Checking total workers
      assert:
        that:
          - item.value.count|int > 0 
        msg: "k8s workers count should be > 0"
      loop: "{{ lookup('dict',vmg_vms_infra, wantlist=True) }}"
      when: item.key | regex_search('(worker)') == 'worker'
      loop_control:
        label: output



# This Playbook creates an in-memory inventory to identify all cluster machines
#
# ASSUMPTIONS:
# Will make use of sudo password in the configs/password.yml in clear text
#

- name: Creating in-memory inventory
  hosts: localhost
  become: no
  vars_files:
    - 'configs/password.yml'
    - 'configs/cloudinit-config.yml'

  vars:
    ansible_become_password: "{{ sudo_password }}"

  tasks:
    - name: Adding controlplane hosts to group 
      add_host:
        name: '{{ item.value.vm_static_ip }}'
        groups: cluster
        ansible_user: '{{ ssh_user_name }}'
      loop: "{{ lookup('dict',cloud_vms_info, wantlist=True) }}"
      when: item.key | regex_search('(master|worker)') in ['master','worker']
      loop_control:
        label: output



# Objective is to configure all k8s cluster VMs before installing the k8s package
#
# ASSUMPTIONS:
# Will make use of sudo password in the configs/password.yml in clear text
#
#


- name: Configuring VMs for Kubernetes
  hosts: cluster
  gather_facts: no
  vars_files:
    - 'configs/password.yml'
    - 'configs/k8s-config.yml'
  vars:
    ansible_ssh_private_key_file: ./do-not-delete/ansible_vms_rsa

  tasks:
    - name: Presistently adding kernel modules for k8s
      copy:
        content: |
          overlay
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf
        mode: '0644'

    - name: Update Kernel to allow a process to bind to a non-local IP address
      copy:
        content: |
          net.ipv4.ip_nonlocal_bind=1
        dest: /etc/sysctl.d/ip_nonlocal_bind.conf
        mode: '0644'

    - name: Running modprobe for kernel modules for k8s
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
          - 'overlay'
          - 'br_netfilter'

    - name: Updating necessary sysctl parameters for k8s 
      sysctl:
        name: "{{ item }}" 
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
      loop:
        - 'net.bridge.bridge-nf-call-ip6tables'
        - 'net.bridge.bridge-nf-call-iptables'
        - 'net.ipv4.ip_forward'
        - 'net.ipv4.ip_nonlocal_bind'

    - name: Add k8s repositories to all cluster nodes
      yum_repository:
        name: kubernetes
        description: Kubernetes package repository
        file: kubernetes
        baseurl: https://pkgs.k8s.io/core:/stable:/v{{ k8s_repo_version }}/rpm/
        enabled: yes
        gpgcheck: yes
        gpgkey: https://pkgs.k8s.io/core:/stable:/v{{ k8s_repo_version}}/rpm/repodata/repomd.xml.key
        repo_gpgcheck: yes
        exclude: 'kubelet kubeadm kubectl cri-tools kubernetes-cni'
        state: present


    - name: Drop SELinux to Permissive mode
      command: setenforce 0
      changed_when: false

    - name: Persistently Set SELinux to Permissive mode
      lineinfile:
        path: /etc/selinux/config
        regexp: "^SELINUX=enforcing" 
        line: "SELINUX=permissive"
        state: present
        backup: yes


    - name: Installing and configuring Containerd
      import_tasks: tasks/configure_docker.yml
      when: cri == 'docker'

    - name: Installing and configuring Containerd
      import_tasks: tasks/configure_containerd.yml
      when: cri == 'containerd'

    - name: Installing and configuring CRI-O
      import_tasks: tasks/configure_cri-o.yml
      when: cri == 'cri-o'

    - name: Installing Kubernetes packages
      yum:
        name:
          - 'kubelet-{{ k8s_package_version }}'
          - 'kubeadm-{{ k8s_package_version }}'
          - 'kubectl-{{ k8s_package_version }}'
          - iproute-tc
        disable_excludes: kubernetes
        state: installed

    - name: Start and enable Kubelet service
      service:
        name: kubelet
        state: started
        enabled: true


    # NOTE: at this point the kubelet service is now in a crashloop and restarting every few seconds, 
    #       as it waits for kubeadm to tell it what to do

