# This Playbook creates an in-memory inventory to list all workers nodes
# This list will be used in the subsequent play
#
# ASSUMPTIONS:
# Will make use of sudo password in the configs/password.yml in clear text
#

- name: Creating in-memory inventory
  hosts: localhost
  gather_facts: no
  become: no
  vars_files:
    - 'configs/password.yml'
    - 'configs/cloudinit-config.yml'

  vars:
    ansible_become_password: "{{ sudo_password }}"

  tasks:
    - name: Adding worker hosts to group 
      add_host:
        name: '{{ item.value.vm_static_ip }}'
        groups: workers
        ansible_user: '{{ ssh_user_name }}'
      loop: "{{ lookup('dict',cloud_vms_info, wantlist=True) }}"
      when: item.key | regex_search('(master|worker)') in ['worker']
      loop_control:
        label: output



# Objective is to join all k8s workers to the control plane
#
# ASSUMPTIONS:
# Will make use of sudo password in the configs/password.yml in clear text
#


- name: Starting with Kubernetes worker configuration
  hosts: workers
  gather_facts: no
  vars_files:
    - 'configs/password.yml'
    - 'configs/k8s-config.yml'

  vars:
    ansible_ssh_private_key_file: ./do-not-delete/ansible_vms_rsa

  tasks:

    - name: Copy join scripts to worker node(s)
      copy:
        src: configs/join_workers.sh
        dest: ~/join_workers.sh
        mode: 0770

    - name: Joining worker nodes to k8s cluster
      shell: '~/join_workers.sh > /root/workers.log'
      changed_when: true
