# This Playbook creates an in-memory inventory consisting of all master nodes
# that will be used in the subsequent play
#
# ASSUMPTIONS:
# Will make use of sudo password in the configs/password.yml in clear text
#

- name: Checking if kubectl needs to be installed on host
  hosts: localhost
  gather_facts: no
  become: no
  vars_files:
    - 'configs/password.yml'
    - 'configs/cloudinit-config.yml'

  tasks:
    - name: Adding controlplane hosts to group
      add_host:
        name: '{{ item.value.vm_static_ip }}'
        groups: masters
        ansible_user: '{{ ssh_user_name }}'
      loop: "{{ lookup('dict',cloud_vms_info, wantlist=True) }}"
      when: item.key | regex_search('(master|worker)') in ['master']
      loop_control:
        label: output




# This Playbook install kubectl on the host machine
#
# ASSUMPTIONS:
# Will make use of sudo password in the configs/password.yml in clear text
# Assumes a k8s master has been properly configured
#

- name: Attempting to install kubectl utility on host
  hosts: '{{ groups.masters[0] }}'
  gather_facts: no
  vars_files:
    - 'configs/password.yml'
    - 'configs/k8s-config.yml'
  tasks:
    - meta: end_play
      when: components.install_kubectl_on_host == false

    - name: Creating local folder on host to store kubeconfig
      file:
        path: ~/.kube
        state: directory
        mode: '0775'
      delegate_to: localhost
      become: false

    - name: Fetching kubeconfig from master to host
      fetch:
        src: /root/.kube/config
        dest: ~/.kube/config
        flat: yes

    - name: Setting Environment variable for k8s access
      lineinfile:
        path: ~/.bashrc
        line: KUBECONFIG=$HOME/.kube/config
        create: yes
        mode: '0644'
      delegate_to: localhost
      become: false

    - name: Add k8s repositories on host machine to install kubectl command
      yum_repository:
        name: kubernetes
        description: Kubernetes package repository
        file: kubernetes
        baseurl: https://pkgs.k8s.io/core:/stable:/v{{ k8s_repo_version }}/rpm/
        enabled: yes
        gpgcheck: yes
        gpgkey: https://pkgs.k8s.io/core:/stable:/v{{ k8s_repo_version}}/rpm/repodata/repomd.xml.key
        repo_gpgcheck: yes
        exclude: 'kubelet kubeadm kubectl cri-tools kubernetes-cni'
        state: present
      delegate_to: localhost
      vars:
        ansible_become_password: "{{ sudo_password }}"

    - name: Installing the kubectl utility on host
      yum:
        name: "kubectl-{{ k8s_package_version }}"
        state: installed
        disable_excludes: kubernetes
      delegate_to: localhost
      vars:
        ansible_become_password: "{{ sudo_password }}"

