    - name: Generating kubeadm init commandline
      template:
        src: templates/kubeadm_init.j2
        dest: tasks/kubeadm_init_cmd.yml
      become: no
      delegate_to: localhost

    - name: Including kubeadm command line
      include_tasks:
        file: tasks/kubeadm_init_cmd.yml

    - name: Adding details to masters join script
      shell: |
        set -o pipefail
        tail -n12 < ~/controlplane.log | head -n3 >> ~/join_masters.sh
      args:
        executable: /bin/bash
      changed_when: true

    - name: Adding details to workers join script
      shell: 'tail -n2 ~/controlplane.log >> ~/join_workers.sh'
      changed_when: true

    - name: Copying masters join script to Controller
      fetch:
        src: ~/join_masters.sh
        dest: ./configs/join_masters.sh
        flat: yes

    - name: Copying workers join script to Controller
      fetch:
        src: ~/join_workers.sh
        dest: ./configs/join_workers.sh
        flat: yes
