#---- Octant Dashboard Variables ----#
octant_url: https://github.com/vmware-archive/octant/releases/download/v0.25.1/octant_0.25.1_Linux-64bit.rpm

# IP of the machine that Octant listens to
octant_listener_ipaddr: '0.0.0.0'

# Hosts allowed to access Octant Dashboard (Use for security)
octant_accepted_hosts: '0.0.0.0'

# Port used by octant Web application
octant_port: 5200

# NOTES: the octant_url: can be made to point to the latest Octant dashboard available or a specific version of Octant



#---- NFS storage Provisioner Variables ----#

nfs_share: '/nfs/storage'
nfs_options: '*(rw,sync,no_subtree_check)'
nfs_permission: '0770'
nfs_prov_repo: 'https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/'
nfs_namespace: nfs-storage-ns
nfs_storageclass_name: nfs-storage


#---- MetalLB Load Balancer Variables ----#
metallb_url: https://raw.githubusercontent.com/metallb/metallb/v0.13.12/config/manifests/metallb-native.yaml
metallb_ipaddr_pool: 192.168.200.130-192.168.200.150


#---- Metric Server Related Variable ----#
metrics_server_url: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

#Use this for Metrics Server in HA mode
#metrics_server_url: 'https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/high-availability-1.21+.yaml'


#---- Kube State Metrics Variables ----#
ksm_repo: https://github.com/kubernetes/kube-state-metrics.git
